export { default as Home }  from './home/Home'
export { default as About }  from './about/About'
export { default as Contact }  from './contact/Contact'
export { default as SignUp }  from './sign-up/Sign-up'
export { default as LogIn}  from './log-in/LogIn'
export { default as ViewAll }  from './view-all/ViewAll'
export { default as ItemDetails }  from './item-details/ItemDetails'
export { default as WishList  } from './wish-list/WishList'
export { default as Cart }  from './cart/Cart'